spring.application.name=licenciasApp
server.servlet.context-path=/BackLicencia
server.port=9098
pServidor = localhost
pPuerto = 5432
pUsuario = jesusvelaztiqui
pBaseDatos = applicencias
pClave = 123

